## 2.3 回帰分析を利用した探索的な効果検証

ここからは回帰分析を用いてどのように効果検証が行われたか Angrist et al. (2002) を例に

```{r}
# 最初の読み込み
# remotes::install_github('itamarcaspi/experimentdatar')

library(pacman)
pacman::p_load(
  experimentdatar,
  broom,
  tidyverse,
  readr
  )
# 最初だけ, ローカルに保存したから後から使う時はもうok
# data("vouchers")
# readr::write_csv(vouchers, './vouchers.csv')
vouchers_df <- readr::read_csv('./vouchers.csv')
```

ではここから論文内容の一部を再現 & プロセスと考え方を追体験

### 2.3.1 PACESによる学費の割引券配布の概要

この論文では，コロンビアで行われた学費の割引券を配る実験によって得られたデータを分析し，受給者の経済的負担に対して補助を行うことの効果を検証している．学校に対して補助を行うべきか，生徒に対して補助を行うべきか...そんな議論の一つ.

1990年代のコロンビアではより高い学費を払って私立学校に通うことがより良い教育を受ける代表的手段であった．このような状況で割引券を配布することは私立通学を増やし，より多くの生徒により質の高い教育をもたらすことが期待される

PACESは応募者の中からランダムに選択したSecondary School(中高)の学生の当選者に私立高校の学費の半分程度を政府が肩代わりするプロジェクトである

割引券を介入としたときの特徴は２つ

1.  割引券は私立学校の価格を大幅に下げること\
    当選グループは私立学校へ通う割合が大きくなりそうだと想定され，受ける教育の質の向上を期待
2.  この仕組みによって学生が落第しないように努力するインセンティブが発生すること\
    落第によって割引券が失効するので，失効した場合には親の所得が減少するため

この例では介入がランダムにアサインされているためRCTを実行しているという設定となる\
しかし，実際のデータは介入実施の数年たった後の調査に回答してくれた結果から得ている．

つまり，調査に回答するか否かの意思決定が当選グループと非当選グループにおいて異なるようであれば，データとして得られるサンプルの傾向にはグループ間で違いが出てしまうことになる

こんなふうに，ランダムに振り分けられたとしても，その後に調査があることからデータにバイアスが発生し，結果としてセレクションバイアスがある下での効果検証となってしまう

以下が vouchersデータセットの内容

| 変数名 | 説明 | 補足 |
|:--:|:---|:---|
| SVY | 電話による調査が行われたか | 調査の方法の影響を除去 |
| HSVISIT | 調査が対面によって行われたか | 調査の方法の影響を除去 |
| DMONTH1-12 | 調査が何月に行われたか | 調査のタイミングの影響を除去 |
| AGE | 調査時の学生の年齢 | セレクションバイアス発生させそう |
| SEX2 | 学生の性別 | セレクションバイアス発生させそう |
| STRATA1-6,MS | 調査対象の親の社会的地位の分類 | セレクションバイアス発生させそう |
